zephyr_7b_beta:
  name: "HuggingFaceH4/zephyr-7b-beta"
  device_map: "auto"
  precision: "bfloat16" 

zephyr_7b_rmu:
  name: "cais/Zephyr_RMU"
  device_map: "auto"
  precision: "bfloat16" 

llama2_7b:
  name: "meta-llama/Llama-2-7b-chat-hf"
  device_map: "auto"
  precision: "bfloat16" 

llama3_tar_bio:
  name: "lapisrocks/Llama-3-8B-Instruct-TAR-Bio-v2"
  tokenizer: "meta-llama/Llama-3.1-8B-Instruct"
  device_map: "auto"
  precision: "bfloat16" 

llama3_8b_rmu:
  name: "ScaleAI/mhj-llama3-8b-rmu"
  device_map: "auto"
  precision: "bfloat16" 

llama3_8b_instruct:
  name: "meta-llama/Meta-Llama-3-8B-Instruct"
  device_map: "auto"
  precision: "bfloat16" 

zephyr_7b_elm:
  name: "baulab/elm-zephyr-7b-beta"
  device_map: "auto"
  precision: "bfloat16" 

mistral_7b_elm:
  name: "baulab/elm-Mistral-7B-v0.1"
  device_map: "auto"
  precision: "bfloat16" 

mistral_7b_v0.1:
  name: "mistralai/Mistral-7B-v0.1"
  device_map: "auto"
  precision: "bfloat16" 

llama3_8b_instruct_elm:
  name: "baulab/elm-Meta-Llama-3-8B-Instruct"
  device_map: "auto"
  precision: "bfloat16" 

llama3_8b_elm:
  name: "baulab/elm-Meta-Llama-3-8B"
  device_map: "auto"
  precision: "bfloat16" 

llama3_8b:
  name: "meta-llama/Meta-Llama-3-8B"
  device_map: "auto"
  precision: "bfloat16" 
